import SessionGuard from "@/components/auth/session-guard";
import LoadingPage from "@/components/loading-page";
import { PublicProviders } from "@/providers/public";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Go Sustainability",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<LoadingPage />}>
          <PublicProviders>
            <SessionGuard>{children}</SessionGuard>
          </PublicProviders>
        </Suspense>
      </body>
    </html>
  );
}
