import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PublicProviders } from "@/providers/public";
import SessionGuard from "@/components/auth/session-guard";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GDI Sustainability",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PublicProviders>
          <Suspense fallback={<div className="h-full bg-red-500 ">Loading...</div>}>
            <SessionGuard>{children}</SessionGuard>
          </Suspense>
        </PublicProviders>
      </body>
    </html>
  );
}
